---
abstract: 'Convert a URL to embedded content'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  File::Find: 1.00
  Module::Find: 0.10
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-LinkEmbedder
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.30
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mojolicious-Plugin-LinkEmbedder
  homepage: https://metacpan.org/release/Mojolicious-Plugin-LinkEmbedder
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/mojolicious-plugin-linkembedder
version: 0.02
